version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'lightGreen'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'lightGreen'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'lightYellow'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#ffffff>in</> {{ .Path }} '
    foreground = 'cyan'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = ''
      style = 'unique'

      [blocks.segments.properties.mapped_locations]
        '~/Downloads' = '󰇚'
        '~/Music' = ''
        '~/dotfiles' = '󱗼'
        '~/mhome' = ''

  [[blocks.segments]]
    template = '<#ffffff>on</> {{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#ff94df'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' <#ff94df><b> </b></>'
      cache_duration = 'none'
      fetch_stash_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'lightGreen'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    foreground = 'red'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
